GET https://atpassignments-1.onrender.com/user-api/users
###
POST https://atpassignments-1.onrender.com/user-api/users
Content-Type: application/json

{
    "name":"nishitha1",
    "email":"nishitha1@gmail.com",
    "dateOfBirth":"2005-01-30",
    "mobileNumber":8929674849
}

###
GET https://atpassignments-1.onrender.com/user-api/users/69a690d4268d4689ba96eef3

###
DELETE https://atpassignments-1.onrender.com/user-api/users/69a690d4268d4689ba96eef3

###activate user
PATCH https://atpassignments-1.onrender.com/user-api/users/69a690d4268d4689ba96eef3

